local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {};
}

gt.Const.Strings.ShieldNames <- [
	"Shield",
	"Bulwark",
	"Protector",
	"Board",
	"Wall",
	"Cover",
	"Safeguard",
	"Guardian",
	"Defender",
	"Ward",
	"Barricade",
	"Barrier",
	"Greatshield",
	"Bastion",
	"Fortress",
	"Guard",
	"Rampart",
	"Keeper",
	"Warden",
	"Carapace"
];
gt.Const.Strings.SwordNames <- [
	"Slasher",
	"Slicer",
	"Blade",
	"Cutter",
	"Cleaver",
	"Sword",
	"Deathdealer",
	"Mercy",
	"Slayer",
	"Edge",
	"Warblade",
	"Longblade",
	"Bloodspiller",
	"Oathkeeper",
	"Glimmer",
	"Reckoning",
	"Avenger",
	"Red Rivers",
	"Stinger",
	"Lightning",
	"Striker",
	"Razor",
	"Edge",
	"Windblade",
	"Swiftblade"
];
gt.Const.Strings.SabreNames <- [
	"Curved Blade",
	"Saber",
	"Beheader",
	"Arched Blade",
	"Crescent",
	"Half Moon",
	"South Star",
	"Shamshir",
	"Scimitar"
];
gt.Const.Strings.CleaverNames <- [
	"Chopper",
	"Ripper",
	"Slasher",
	"Slicer",
	"Cutter",
	"Cleaver",
	"Beheader",
	"Ravager",
	"Bloodspiller",
	"Bloodthirster",
	"Madness",
	"Carver",
	"War Cleaver",
	"Gut-Seeker",
	"Fleshcutter",
	"Meat Axe",
	"Mincer",
	"Hacker",
	"Lacerator",
	"Mangler",
	"Gasher",
	"Mutilator",
	"Maimer",
	"Tormentor",
	"Render"
];
gt.Const.Strings.WhipNames <- [
	"Whip",
	"Tongue",
	"Snake",
	"Lightning",
	"Strangler",
	"Reach",
	"Painbringer",
	"Punisher",
	"Castigator"
];
gt.Const.Strings.AxeNames <- [
	"Splitter",
	"Chopper",
	"Axe",
	"Menfeller",
	"Fury",
	"Vengeance",
	"Slayer",
	"Reaver",
	"Harbinger",
	"Ravager",
	"Skullsplitter",
	"Conqueror",
	"Deathbringer",
	"Widowmaker",
	"Destroyer",
	"Shieldbreaker",
	"Crescent"
];
gt.Const.Strings.LongaxeNames <- [
	"Longaxe",
	"Fury",
	"Vengeance",
	"Reaver",
	"Harbinger",
	"Ravager",
	"Skullsplitter",
	"Deathbringer",
	"Widowmaker",
	"Shieldbreaker",
	"Spath",
	"Poleblade",
	"Shafted Axe",
	"Headcleaver",
	"Ripper",
	"Splinter",
	"Cleaver",
	"Thunderbringer",
	"Breaker",
	"Domesplitter"
];
gt.Const.Strings.ThrowingAxeNames <- [
	"Axes",
	"Blades",
	"Splitters",
	"Spinning Death",
	"Rippers",
	"Shredders",
	"Fury",
	"Ravagers",
	"Harbingers",
	"Widowmakers",
	"Torrent",
	"Crescent",
	"Brutality",
	"Breachers",
	"Edges",
	"Slayers"
];
gt.Const.Strings.SpearNames <- [
	"Spike",
	"Impaler",
	"Spear",
	"Stabber",
	"Shaft",
	"Spit",
	"Skewer",
	"Stake",
	"Thorn",
	"Barb",
	"Quill",
	"Longspear",
	"Swift spike",
	"Bladeflurry",
	"Defender",
	"Stinger",
	"Pin"
];
gt.Const.Strings.PikeNames <- [
	"Lance",
	"Pole",
	"Staff",
	"Stake",
	"Impaler",
	"Warpike",
	"Pike",
	"Ray",
	"Spout",
	"Stinger",
	"Spine",
	"Longpike",
	"Heartspike",
	"Eye Poker",
	"Spire",
	"Silver Lance",
	"Pricker"
];
gt.Const.Strings.BillNames <- [
	"Thresher",
	"Bill",
	"Billhook",
	"Poleblade",
	"Polearm",
	"Bardiche",
	"Voulge",
	"Reach",
	"Willbreaker",
	"Bloodspiller",
	"Hacker",
	"Chopper",
	"Foe Feller",
	"Mutilater",
	"Whacker",
	"Mangler",
	"Gasher"
];
gt.Const.Strings.GreatswordNames <- [
	"Greatsword",
	"Zweihander",
	"Blade",
	"Longblade",
	"Slayer",
	"Vanquisher",
	"Beheader",
	"Executioner",
	"Defender",
	"Orcslayer",
	"Honor",
	"Claymore",
	"Thug\'s Bane",
	"Long Reach",
	"Splitter",
	"Warsword",
	"Bidenhander",
	"Gassenhauer"
];
gt.Const.Strings.WarbrandNames <- [
	"Warbrand",
	"Kriegsmesser",
	"Beidhander",
	"Blade",
	"Longblade",
	"Slayer",
	"Vanquisher",
	"Beheader",
	"Calamity",
	"Witherbrand",
	"Warblade",
	"Windslasher",
	"Cutlass",
	"Edge",
	"Quickblade",
	"Striker",
	"Fleshripper",
	"Fleshrender"
];
gt.Const.Strings.DaggerNames <- [
	"Splinter",
	"Thorn",
	"Wedge",
	"Gouge",
	"Chisel",
	"Sting",
	"Dirk",
	"Bodkin",
	"Snickersnee",
	"Dagger",
	"Bloodletter",
	"Oathbreaker",
	"Venom",
	"Cunning",
	"Avenger",
	"Backstabber",
	"Heartseeker",
	"Stiletto",
	"Shank",
	"Shiv",
	"Needle",
	"Estoc"
];
gt.Const.Strings.CrossbowNames <- [
	"Bolter",
	"Impaler",
	"Spitter",
	"Nailer",
	"Thrower",
	"Shooter",
	"Catapult",
	"Balista",
	"Crossbow",
	"Tiebreaker",
	"Penetrator",
	"Betrayer",
	"Spearthrower",
	"Skyfire",
	"Messenger",
	"Repeater",
	"Giant Hunter",
	"Arbalest",
	"Reach",
	"Emissary"
];
gt.Const.Strings.BowNames <- [
	"Reach",
	"Bend",
	"Greatbow",
	"Longbow",
	"Warbow",
	"Dart",
	"Grasp",
	"Flight",
	"Recurve",
	"Whisperwind",
	"Startrail",
	"Warsong",
	"Barrage",
	"Heartpiercer",
	"Avenger",
	"Swiftwind",
	"Shooter",
	"Heartstriker",
	"Stinger",
	"Comet",
	"Meteor",
	"Stormbringer",
	"Hailbringer",
	"Hailstorm",
	"Arrowfall",
	"Cord",
	"Sinew",
	"Tendon"
];
gt.Const.Strings.FlailNames <- [
	"Flail",
	"Basher",
	"Smacker",
	"Whip",
	"Justice",
	"Purifier",
	"Malice",
	"Harvester",
	"Lament",
	"Hatred",
	"Reckoning",
	"Blind Justice",
	"Salvation",
	"Thrasher",
	"Flogger",
	"Spanker",
	"Trouncer",
	"Reaper",
	"Castigater",
	"Punisher",
	"Flying Star",
	"Assaulter",
	"Bruiser"
];
gt.Const.Strings.MaceNames <- [
	"Basher",
	"Smasher",
	"Crusher",
	"Club",
	"Mace",
	"Cudgel",
	"Manslayer",
	"Skullcrusher",
	"Maul",
	"Mauler",
	"Domination",
	"Desolation",
	"Warmace",
	"Baton",
	"Scepter",
	"Royal Mace",
	"Banger",
	"Clobber",
	"Knocker"
];
gt.Const.Strings.HammerNames <- [
	"Hammer",
	"Sledge",
	"Mallet",
	"Crusher",
	"Armorbreaker",
	"Beak",
	"Mauler",
	"Cataclysm",
	"Battlehammer",
	"Knightslayer",
	"Pummeler",
	"Iron eater",
	"Bill",
	"Pecker",
	"Iron warper",
	"Scruncher",
	"Sunderer"
];
gt.Const.Strings.JavelinNames <- [
	"Thorns",
	"Spikes",
	"Needles",
	"Javelins",
	"Throwing Spears",
	"Stakes",
	"Darts",
	"Barbs",
	"Spines",
	"Nails",
	"Lances",
	"Harpoons"
];
gt.Const.Strings.FencingSwordNames <- [
	"Stinger",
	"Flurry",
	"Thorn",
	"Pincer",
	"Edge",
	"Striker",
	"Blade",
	"Heartseeker",
	"Bloodspiller",
	"Gapcloser",
	"Grace",
	"Swiftblade"
];
gt.Const.Strings.PolehammerNames <- [
	"Smasher",
	"Crusher",
	"Tremor",
	"Earthshaker",
	"Ironbiter",
	"Beak",
	"Hammer",
	"Sunderer",
	"Gatecrasher",
	"Battlehammer",
	"Thunderer"
];
gt.Const.Strings.ThreeHeadedFlailNames <- [
	"Ochsenherde",
	"Nine Tailed Cat",
	"Flesh Tearer",
	"Choir",
	"Hail",
	"Cascade",
	"Stampede",
	"Shower",
	"Brutalizer",
	"Warband"
];
gt.Const.Strings.SpetumNames <- [
	"Spike",
	"Trident",
	"Skewer",
	"Phalanx",
	"Spine",
	"Longpike",
	"Heartspike",
	"Eye Poker",
	"Spire",
	"Silver Lance",
	"Pricker"
];
gt.Const.Strings.TwoHandedFlailNames <- [
	"Headcrusher",
	"Shieldbender",
	"Crusher",
	"Skullcracker",
	"Bonegrinder",
	"Maimer",
	"Flail",
	"Punisher",
	"Basher",
	"Whip",
	"Harvester"
];
gt.Const.Strings.TwoHandedMaceNames <- [
	"Skullwarper",
	"Crusher",
	"Stomper",
	"Cudgel",
	"Bludgeon",
	"Pillar",
	"Wacker",
	"Warmace",
	"Giant\'s Mace",
	"Stonefist",
	"Pummel",
	"Earthshaker"
];
gt.Const.Strings.WarscytheNames <- [
	"Warscythe",
	"Reaper",
	"Sickle",
	"Blade",
	"Edge",
	"Scythe",
	"Harvester",
	"Crescent"
];
gt.Const.Strings.HandgonneNames <- [
	"Cannon",
	"Firebreather",
	"Powderstick",
	"Roar",
	"Thunder",
	"Rod of Fire",
	"Dragontongue",
	"Gonne",
	"Thunderrod",
	"Firespitter"
];
gt.Const.Strings.SwordlanceNames <- [
	"Bladed Staff",
	"Bladed Lance"
];
this.Const.Strings.SwordlanceNames.extend(this.Const.Strings.WarscytheNames);
gt.Const.Strings.OldWeaponPrefix <- [
	"Ancient",
	"Forefather\'s",
	"Heritage",
	"Time-honored",
	"Antique",
	"Immemorial",
	"Dead Lord\'s",
	"Long lost",
	"Forgotten",
	"Old",
	"Cold-forged",
	"The",
	"Ancient",
	"Dire",
	"Grim",
	"Venerable",
	"Archaic",
	"Relic",
	"Buried",
	"Precursor\'s",
	"Forebearer\'s",
	"Battle-scarred",
	"Curio",
	"Remnant",
	"Keepsake",
	"Empire\'s",
	"Legion\'s",
	"Ancient"
];
gt.Const.Strings.BarbarianPrefix <- [
	"Forefather\'s",
	"Conqueror\'s",
	"Chieftain\'s",
	"Warlord\'s",
	"Champion\'s",
	"Ancestors\'",
	"Fire Bringer\'s",
	"Despoiler\'s",
	"Blood-drenched",
	"Reaver\'s",
	"Frozen",
	"Chilling",
	"Tribal",
	"Barbarian",
	"Bloodied",
	"Chosen"
];
gt.Const.Strings.BarbarianSuffix <- [
	"of the North",
	"of Old",
	"of Rage",
	"of Slaughter",
	"of Carnage",
	"of the Gods",
	"of Defiance",
	"of Heroes"
];
gt.Const.Strings.SouthernPrefix <- [
	"Southern",
	"Nomad\'s",
	"Manhunter\'s",
	"Gladiator\'s",
	"Assassin\'s",
	"Gilded",
	"Desert",
	"True",
	"The",
	"Deadly",
	"Well-crafted",
	"Masterwork",
	"Well-balanced",
	"Honed",
	"Famed",
	"Trusty",
	"Glorious",
	"Ravenous",
	"Bitter",
	"Infamous",
	"Marvellous",
	"Vizier\'s",
	"Oversized",
	"Bloody",
	"Cruel",
	"Murderous",
	"Malignant",
	"Violent",
	"Lethal",
	"Ominous",
	"Grisly",
	"Magnificent",
	"Exquisite"
];
gt.Const.Strings.SouthernSuffix <- [
	"of the South",
	"of the Gilder",
	"of the Desert",
	"of the Sands",
	"of the Rising Sun",
	"of the Morning",
	"of the Oasis",
	"of the Stars",
	"of the Moon",
	"of Splendor",
	"of Magnificence",
	"of Cleansing Fire",
	"of Divine Will"
];
gt.Const.Strings.GoblinWeaponPrefix <- [
	"Razor-sharp",
	"Quick",
	"Pointy",
	"Stinging",
	"Barbed",
	"Spiky",
	"Sly",
	"Backstabbing",
	"Assassin\'s",
	"Cruel",
	"Perfidious",
	"Sticky",
	"Vile",
	"Malicious"
];
gt.Const.Strings.RandomWeaponPrefix <- [
	"The",
	"Deadly",
	"Well-crafted",
	"Masterwork",
	"Well-balanced",
	"Honed",
	"Grim",
	"Sellswords\'s",
	"Famed",
	"Trusty",
	"Champion\'s",
	"Battle-forged",
	"Northern",
	"Raider\'s",
	"Unsung Hero\'s",
	"Glorious",
	"Ravenous",
	"Bitter",
	"Infamous",
	"Marvellous",
	"Oversized",
	"Bloody",
	"Cruel",
	"Mortal",
	"Murderous",
	"Malignant",
	"Savage",
	"Violent",
	"Lethal",
	"Ominous",
	"Gruesome",
	"Grisly",
	"Magnificent",
	"Exquisite"
];
gt.Const.Strings.RandomArmorPrefix <- [
	"Captain\'s",
	"Masterwork",
	"Well-crafted",
	"Sturdy",
	"Veteran\'s",
	"Master-forged",
	"Stalwart",
	"Iron Guard\'s",
	"Famed",
	"Infamous",
	"Mercenary\'s",
	"Bleak Wolf\'s",
	"Heritage",
	"Battle-hardened",
	"Sellsword\'s",
	"Imperishable",
	"Rugged",
	"Unruly",
	"Trusty",
	"Champion\'s",
	"The",
	"Glorious",
	"Marvellous",
	"Distinguished",
	"Illustrious",
	"Dignified",
	"Venerable",
	"Esteemed",
	"Revered",
	"Cherished",
	"Masterstroke",
	"Monumental",
	"Stern"
];
gt.Const.Strings.RandomShieldPrefix <- [
	"The",
	"Sturdy",
	"Masterwork",
	"Firm",
	"Unbreakable",
	"Battle-forged",
	"Hardened",
	"Stalwart",
	"Famed",
	"Insurmountable",
	"Glorious",
	"Hulking",
	"Stout",
	"Solid",
	"Unyielding",
	"Shatterproof",
	"Unshakeable",
	"Incorruptible",
	"Callous",
	"Unbending",
	"Colossal"
];
gt.Const.Strings.WardogNames <- [
	"Bull",
	"Brock",
	"Bane",
	"Duke",
	"Fang",
	"Hyde",
	"Gruff",
	"Ghost",
	"Grond",
	"Wind",
	"Bragge",
	"Brazen",
	"Blaze",
	"Bones",
	"Brant",
	"Dash",
	"Drake",
	"Finch",
	"Jager",
	"Biter",
	"Teal",
	"Earl",
	"Faust",
	"Jaws",
	"Runner",
	"Rags",
	"Olof",
	"Silver",
	"King",
	"Wolf",
	"Hound",
	"Mutt",
	"Thorn",
	"Ritter",
	"Varg",
	"Brawler",
	"Lord",
	"Cassio",
	"Claw",
	"Lasher",
	"Skoll",
	"Bonefur",
	"Spike",
	"Grayfang",
	"Spirit",
	"Seff",
	"Howler",
	"Strider",
	"Cujo",
	"Snarrler",
	"Haze",
	"Misty",
	"Witherfang",
	"Amarog",
	"Grizzle",
	"Longfang",
	"Chomper",
	"Redtooth",
	"Maugrim",
	"Shiv",
	"Snapper",
	"Catchaser",
	"Quickpaw",
	"Stormtail"
];


gt.Const.Strings.ArtifactAxeNames <- [
	"Skullrender",
	"Guttler",
	"Ogre Bane",
	"Juggernaut",
	"Ragnar's Call",
	"Gorefiend",
	"Star Hewer",
	"Reaper",
	"Headsman",
	"Bravura"
];
gt.Const.Strings.ArtifactWhipNames <- [
	"The Golden Lasso",
	"Discipline",
	"Lion Tamer",
	"Qilinbian",
	"Scourge"
];
gt.Const.Strings.ArtifactPolearmNames <- [
	"The Whirlwind",
	"Bec de Corbin",
	"Glaive-Guisarme",
	"Bohemian Earspoon",
	"Thalassocrat",
	"Gae Bolg",
	"Gae Derg",
	"Amenonuhoko",
	"Gungnir",
	"Rhongomyniad",
	"Vel"
];
gt.Const.Strings.ArtifactSwordNames <- [
	"Excalibur",
	"Joyeuse",
	"Greyswandir",
	"Orcrist",
	"Durandal",
	"Arondright",
	"Amanomurakumo",
	"Dragnipur",
	"Callandor",
	"Ice",
	"Glamdrang",
	"Narsil",
	"Balmung",
	"Hrondil",
	"Caliburn",
	"Ridill",
	"Zenmetsu",
	"Almace",
	"Burtgang",
	"Ragnarok",
	"Lionheart",
	"Humility",
	"Gram",
	"Buster Sword",
	"Tizona",
	"Calada",
	"Chrysaor",
	"Fragarach",
	"Clarent",
	"Coreiseuse",
	"Secace",
	"Courtain",
	"Tyrfing",
	"Hauteclaire",
	"Harpe"
];
gt.Const.Strings.ArtifactCrossbowNames <- [
	"Hellrack",
	"Buriza-Do Kyanon",
	"Demon Machine",
	"Gastraphetes",
	"Reason",
	"Imati",
	"Illap"
];
gt.Const.Strings.ArtifactDaggerNames <- [
	"Athame",
	"Carnwennan",
	"Parazonium",
	"Misericorde",
	"Mandau",
	"Golad",
	"Tiriosh",
	"Kingslayer"
];
gt.Const.Strings.ArtifactFlailNames <- [
	"Holy Water Sprinkler",
	"Stormlash",
	"Scourge",
	"Golden Flence",
	"Cranium Basher"
];
gt.Const.Strings.ArtifactThrownNames <- [
	"Thunderbolt",
	"Tathlum",
	"Sagitta",
	"Kenkonken",
	"Vajra"
];
gt.Const.Strings.ArtifactMaceNames <- [
	"Echoing Fury",
	"Asclepius",
	"Gada",
	"Caduceus",
	"Was",
	"The Silver Hand",
	"Shillelagh"
];
gt.Const.Strings.ArtifactOrcNames <- [
	"Mancarver",
	"Slash",
	"Skitch",
	"Gash",
	"Gitsnick",
	"Karg",
	"Crack",
	"Crunch",
	"Smish"
];
gt.Const.Strings.ArtifactSpearNames <- [
	"Aram",
	"Gungnir",
	"Longinus",
	"Rhongomiant",
	"Areadbhar",
	"Crann Buidhe",
	"Gae Assail",
	"Nihongo"
];
gt.Const.Strings.ArtifactHammerNames <- [
	"Mjollnir",
	"Ukonvasara",
	"Steeldriver",
	"The Furnace",
	"Sunder",
	"Doom Hammer",
	"Ironfoe",
	"Stormherald",
	"Storm's End"
];
gt.Const.Strings.ArtifactBowNames <- [
	"Eurytos",
	"Artemis",
	"Houyi",
	"Eros",
	"Rhok'delar",
	"Heartstriker",
	"Yoichinoyumi",
	"Loxley"
];
gt.Const.Strings.ArtifactShieldNames <- [
	"Aegis",
	"Hoplon",
	"Ancile",
	"Pridwen",
	"Evalach",
	"Svalinn",
	"Bulwark",
	"Ward"
];
gt.Const.Strings.ArtifactOrcShieldNames <- [
	"Clang",
	"Pillar",
	"No",
	"Grunt",
	"Gork"
];