#!/usr/bin/env python3
"""Scan BB/XBE/Legends/necro background and trait files, extract m.Titles counts,
write built-in.nut for use by tools.nut."""

import re
import os

BBM = "/home/suor/projects/bbm"
SOURCES = [
    (f"{BBM}/base/__data_014/scripts/skills/backgrounds", f"{BBM}/legends/mod_legends/hooks/skills/backgrounds"),
    (f"{BBM}/base/__data_014/scripts/skills/traits",      f"{BBM}/legends/mod_legends/hooks/skills/traits"),
    (f"{BBM}/xbe/scripts/skills/backgrounds/hackflows",   None),
    (f"{BBM}/mods/necro/scripts/skills/backgrounds",      None),
]


def extract(path):
    """Return (factor, title_count) from a skill file, or None if not a skill file."""
    try:
        text = open(path).read()
    except FileNotFoundError:
        return None

    m_id = re.search(r'\.m\.ID\s*=\s*"([^"]+)"', text)
    if not m_id:
        return None

    m_titles = re.search(r'\.m\.Titles\s*=\s*(\[[\s\S]*?\]|[^\[;]+;)', text)
    if not m_titles:
        return None

    block = m_titles.group(1).strip()
    count = '?' if not block.startswith('[') else len(re.findall(r'"[^"]*"', block))
    return m_id.group(1), count


results = {}  # factor -> count

for directory, override_dir in SOURCES:
    if not os.path.isdir(directory):
        continue
    for filename in os.listdir(directory):
        if not filename.endswith(".nut"):
            continue
        result = (override_dir and extract(f"{override_dir}/{filename}")) \
              or extract(f"{directory}/{filename}")
        if result:
            factor, count = result
            results[factor] = count

# Write built-in.nut
with open("built-in.nut", "w") as f:
    f.write("// Auto-generated by gen_built_in.py — do not edit\n")
    f.write("// Count of m.Titles per factor from BB/XBE/Legends source files\n")
    f.write("// '?' means titles come from a shared constant (non-empty but count unknown)\n")
    entries = [f'    ["{f}"] = {"\"?\"" if c == "?" else c}' for f, c in sorted(results.items())]
    f.write("::BuiltInTitles <- {\n")
    f.write(",\n".join(entries) + "\n")
    f.write("}\n")

print(f"Written built-in.nut with {len(results)} entries")
