#!/usr/bin/env python3
"""Scan BB/XBE/Legends background and trait files, extract m.Titles counts,
write external.nut for use by tools.nut."""

import re
import os

BBM = "/home/suor/projects/bbm"
BB_BACKGROUNDS  = f"{BBM}/base/__data_014/scripts/skills/backgrounds"
BB_TRAITS       = f"{BBM}/base/__data_014/scripts/skills/traits"
LEG_BACKGROUNDS = f"{BBM}/legends/mod_legends/hooks/skills/backgrounds"
LEG_TRAITS      = f"{BBM}/legends/mod_legends/hooks/skills/traits"
XBE_BACKGROUNDS = f"{BBM}/xbe/scripts/skills/backgrounds/hackflows"


def count_titles(path):
    """Return count of strings in m.Titles = [...], or None if not present."""
    try:
        text = open(path).read()
    except FileNotFoundError:
        return None
    m = re.search(r'\.m\.Titles\s*=\s*(\[[\s\S]*?\]|[^\[;]+;)', text)
    if not m:
        return None
    block = m.group(1).strip()
    if not block.startswith('['):
        return '?'  # reference like this.Const.Strings.BarbarianTitles
    return len(re.findall(r'"[^"]*"', block))


def bg_factor(name):
    return "background." + name

def trait_factor(name):
    return "trait." + name

def stem(filename, suffix):
    return filename[:-len(suffix)] if filename.endswith(suffix) else None


results = {}  # factor -> count

# Vanilla backgrounds: Legends hooks override BB
for filename in os.listdir(BB_BACKGROUNDS):
    name = stem(filename, "_background.nut")
    if not name:
        continue
    factor = bg_factor(name)
    leg_path = f"{LEG_BACKGROUNDS}/{filename}"
    bb_path  = f"{BB_BACKGROUNDS}/{filename}"
    count = count_titles(leg_path) or count_titles(bb_path)
    if count is not None:
        results[factor] = count

# XBE hackflows backgrounds
for filename in os.listdir(XBE_BACKGROUNDS):
    name = stem(filename, "_background.nut")
    if not name:
        continue
    factor = bg_factor("hackflows_" + name)
    count = count_titles(f"{XBE_BACKGROUNDS}/{filename}")
    if count is not None:
        results[factor] = count

# Traits: Legends hooks override BB
if os.path.isdir(BB_TRAITS):
    for filename in os.listdir(BB_TRAITS):
        name = stem(filename, "_trait.nut")
        if not name:
            continue
        factor = trait_factor(name)
        leg_path = f"{LEG_TRAITS}/{filename}" if os.path.isdir(LEG_TRAITS) else ""
        bb_path  = f"{BB_TRAITS}/{filename}"
        count = (count_titles(leg_path) if leg_path else None) or count_titles(bb_path)
        if count is not None:
            results[factor] = count

# Write external.nut
with open("external.nut", "w") as f:
    f.write("// Auto-generated by gen_external.py — do not edit\n")
    f.write("// Count of m.Titles per factor from BB/XBE/Legends source files\n")
    f.write("// '?' means titles come from a shared constant (non-empty but count unknown)\n")
    entries = []
    for factor in sorted(results):
        count = results[factor]
        val = '"?"' if count == '?' else str(count)
        entries.append(f'    ["{factor}"] = {val}')
    f.write("::ExternalTitles <- {\n")
    f.write(",\n".join(entries) + "\n")
    f.write("}\n")

print(f"Written external.nut with {len(results)} entries")
