#!/usr/bin/env python3
"""Scan BB/XBE/Legends/necro background and trait files, extract m.Titles counts,
write built-in.nut for use by tools.nut."""

import re
import os

# Read ../.env
env = {}
with open(os.path.join(os.path.dirname(__file__), "../.env")) as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            env[k] = v.replace("\\ ", " ")

SOURCES = [
    env["SCRIPTS_DIR"],
    env["LEGENDS_DIR"],
    env["XBE_DIR"],
    os.path.join(os.path.dirname(__file__), "../necro/scripts"),
]
SUBDIRS = ["skills/backgrounds", "skills/traits"]


def extract(path):
    """Return (factor, title_count) from a skill file, or None if not a skill file."""
    try:
        text = open(path).read()
    except FileNotFoundError:
        return None

    m_id = re.search(r'\.m\.ID\s*=\s*"([^"]+)"', text)
    if not m_id:
        return None

    m_titles = re.search(r'\.m\.Titles\s*=\s*(\[[\s\S]*?\]|[^\[;]+;)', text)
    if not m_titles:
        return None

    block = m_titles.group(1).strip()
    count = '?' if not block.startswith('[') else len(re.findall(r'"[^"]*"', block))
    return m_id.group(1), count


results = {}  # factor -> count

for base_dir in SOURCES:
    for subdir in SUBDIRS:
        directory = os.path.join(base_dir, subdir)
        if not os.path.isdir(directory):
            continue
        for root, dirs, files in os.walk(directory):
            for filename in files:
                if not filename.endswith(".nut"):
                    continue
                result = extract(os.path.join(root, filename))
                if result:
                    factor, count = result
                    results[factor] = count

# Write built-in.nut
with open("built-in.nut", "w") as f:
    f.write("// Auto-generated by gen_built_in.py — do not edit\n")
    f.write("// Count of m.Titles per factor from BB/XBE/Legends source files\n")
    f.write("// '?' means titles come from a shared constant (non-empty but count unknown)\n")
    entries = [f'    ["{f}"] = {"\"?\"" if c == "?" else c}' for f, c in sorted(results.items())]
    f.write("::BuiltInTitles <- {\n")
    f.write(",\n".join(entries) + "\n")
    f.write("}\n")

print(f"Written built-in.nut with {len(results)} entries")
