MOD_NAME = perma_hackflow
URL = https://www.nexusmods.com/battlebrothers/mods/855
TAG_NAME = perma
SOURCES = perma_hackflow scripts

include ../Makefile.common

check:
	@rosetta -qc perma_hackflow/rosetta_ru.nut .
