MOD_NAME = bro_studio
TAG_NAME = bro-studio
SOURCES = bro_studio gfx scripts ui
INCLUDES = levelup_changes
SUBDIR = scripts/\!mods_preload

include ../Makefile.common

check:
	@rosetta -qc bro_studio/rosetta_ru.nut .
